name: Build Client

on:
  push:
    branches:
      - master
    paths:
      - 'client/**'

  workflow_dispatch:

jobs:
  build:
    uses: wxn0brP/workflow-dist/.github/workflows/build-ts.yml@main
    with:
      scriptsHandling: "remove-all"
      branch: "dist-client"
      path: "client"
      out: ".."